name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # Esto hace que el workflow se active al hacer push en la rama main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build de la imagen Docker
        run: docker build -t tania1988/calculadora:latest .

      - name: Push a Docker Hub
        run: docker push tania1988/calculadora:latest
